# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  core.twig_extension:
          class: Blog\CoreBundle\Twig\AppExtension
          public: false
          tags:
              - { name: twig.extension }